USE [master]
GO

/****** Object:  Database [mvctutorialdb]    Script Date: 7/9/2017 11:05:49 PM ******/
CREATE DATABASE [mvctutorialdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'mvctutorialdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MYLOCALDB\MSSQL\DATA\mvctutorialdb.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'mvctutorialdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MYLOCALDB\MSSQL\DATA\mvctutorialdb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [mvctutorialdb] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [mvctutorialdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [mvctutorialdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mvctutorialdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mvctutorialdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mvctutorialdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mvctutorialdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [mvctutorialdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [mvctutorialdb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [mvctutorialdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mvctutorialdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mvctutorialdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mvctutorialdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [mvctutorialdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mvctutorialdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mvctutorialdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mvctutorialdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mvctutorialdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [mvctutorialdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mvctutorialdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [mvctutorialdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [mvctutorialdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [mvctutorialdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mvctutorialdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [mvctutorialdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [mvctutorialdb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [mvctutorialdb] SET  MULTI_USER 
GO

ALTER DATABASE [mvctutorialdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [mvctutorialdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [mvctutorialdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [mvctutorialdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [mvctutorialdb] SET  READ_WRITE 
GO

